### ISSUE TITLE
make check: ERROR:  schema "topo_update" does not exist (lack of submodules not properly handled)

### ISSUE THREAD

**Issue by strk** [larsop/resolve-overlap-and-gap#11]
In master branch, targetting PostgreSQL 12:
```
$ make check
...
Creating database 'nibio_reg' 
Preparing db 'nibio_reg' using: CREATE EXTENSION postgis
PostgreSQL 12.2 (Ubuntu 12.2-2.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
  Postgis 3.1.0dev - r3.1.0alpha1-63-gb6b33b0dc - 2020-04-24 09:47:45
  scripts 3.1.0dev 3.1.0alpha1-63-gb6b33b0dc
  GEOS: 3.9.0dev-CAPI-1.14.0
  PROJ: 7.0.0

Running tests

 ./resolve_overlap_and_gap . failed (Errors while running sql script ./resolve_overlap_and_gap-pre.sql: /tmp/pgis_reg/test_1_tmp)
-----------------------------------------------------------------------------
CREATE TYPE
CREATE TYPE
CREATE TYPE
CREATE FUNCTION
CREATE SCHEMA
GRANT
CREATE FUNCTION
COMMENT
CREATE TYPE
CREATE TYPE
CREATE TYPE
CREATE TYPE
CREATE TYPE
CREATE TYPE
COMMENT
COMMENT
COMMENT
CREATE FUNCTION
DROP FUNCTION
DROP FUNCTION
ERROR:  schema "topo_update" does not exist
```

**Comment by strk** [comment]
Indeed I don't find any `create schema topo_update` statement in test SQL files.

**Comment by larsop** [comment]
It should be in resolve_overlap_and_gap-pre.sql 

grep -i 'create schema' resolve_overlap_and_gap-pre.sql 
-- create schema for topo_rein data, tables, ....
CREATE SCHEMA topo_rein;
-- create schema for topo_update data, tables, .... 
CREATE SCHEMA topo_update;
  CREATE SCHEMA test_data;

**Comment by larsop** [comment]
I run the tests with this command

./run_test.pl --verbose --spatial_ref_sys -topology resolve_overlap_and_gap

**Comment by larsop** [comment]
> I run the tests with this command
> 
> ./run_test.pl --verbose --spatial_ref_sys -topology resolve_overlap_and_gap

It also works with make check for mee.

Larss-MacBook-Pro:regress lop$ make check
mkdir -p ../loader; \
	touch ../loader/shp2pgsql
chmod +x ../loader/shp2pgsql
touch ../loader/pgsql2shp
chmod +x ../loader/pgsql2shp
POSTGIS_REGRESS_DB=nibio_reg ./run_test.pl -v --spatial_ref_sys --extension --topology  ./resolve_overlap_and_gap
PATH is /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/usr/local/Cellar/parallel/20140722/bin/
Checking for shp2pgsql ... found
Checking for pgsql2shp ... found
TMPDIR is /tmp/pgis_reg
Creating database 'nibio_reg' 
Preparing db 'nibio_reg' using: CREATE EXTENSION postgis
PostgreSQL 12.1 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.16), 64-bit
  Postgis 3.0.0 - r17983 - 2019-11-22 18:42:24
  scripts 3.0.0 r17983
  GEOS: 3.8.0-CAPI-1.13.1 
  PROJ: 6.3.0

Running tests

 ./resolve_overlap_and_gap ... ok 
 uninstall .. ok (4725)

Run tests: 2
Failed: 0

**Comment by strk** [comment]
Note I'm still not having the submodules downloaded/updated. Intentionally to improve experience in that case (if something is required, failures should occur earlier)

**Comment by larsop** [comment]
Yes I agree with you, but I am not sure about how to do it. We may take this  later when we resolved the problem with invalid MultiPolygons .

**Comment by strk** [comment]
On Fri, Apr 24, 2020 at 04:03:48AM -0700, Lars Aksel Opsahl wrote:
> It should be in resolve_overlap_and_gap-pre.sql 
> 
> grep -i 'create schema' resolve_overlap_and_gap-pre.sql 
> -- create schema for topo_rein data, tables, ....
> CREATE SCHEMA topo_rein;
> -- create schema for topo_update data, tables, .... 
> CREATE SCHEMA topo_update;
>   CREATE SCHEMA test_data;

Not in mine:

```
$ grep -i 'create schema' resolve_overlap_and_gap-pre.sql
-- create schema for topo_rein data, tables, ....
CREATE SCHEMA topo_rein;
  CREATE SCHEMA test_data;
```

That file is the one we just put in .gitignore, so, I guess
the generator script (resolve_overlap_and_gap-pre.pl?) _silently_
fails to fully generate it (due to lack of submodules I guess).

**Comment by strk** [comment]
On Fri, Apr 24, 2020 at 04:32:40AM -0700, Lars Aksel Opsahl wrote:
> Yes I agree with you, but I am not sure about how to do it. We may take this  later when we resolved the problem with invalid MultiPolygons .

Ok let's keep this ticket open to fix that.
I confirm that fetching submodules (git submodule update)
does result in a correct -pre.sql file being generated.

**Comment by strk** [comment]
Note that my `make check` is still running (after lunch break, > 1 hour) and keeping CPU busy. Is this the same experience you have ? This is against `PostgreSQL-12` with default configuration and `Postgis 3.0.0 - r17983` with `GEOS: 3.8.0-CAPI-1.13.1`

**Comment by larsop** [comment]
No it should take less than a minute, but on https://travis-ci.org/github/larsop/resolve-overlap-and-gap it takes around two minutes

**Comment by larsop** [comment]
As I read it this is solved by your fix in the  parallel code.

**Comment by strk** [comment]
I'm not sure this is to be considered fixed. To test we need to clone the main repository (without submodules) and run `make check` from there.

Expected behaviour: receive an error message mentioning lack of submodules and hinting about how to fetch the submodules.

Current behaviour: receive a misleading erro rabout "topo_update" schema not existing.

**Comment by strk** [comment]
This bug will be fixed by merging https://github.com/larsop/resolve-overlap-and-gap/pull/14
