### ISSUE TITLE
SubtransControlLock and performance problems

### ISSUE THREAD

**Issue by strk** [larsop/resolve-overlap-and-gap#2]
As reported by @larsop in https://www.postgresql.org/message-id/HE1P189MB0266B070D1452B04A7C9F6D99D170@HE1P189MB0266.EURP189.PROD.OUTLOOK.COM there seem to be an excess of subtransactions slowing down operations.

This ticket is to further research the topic and find ways to reduce them.

**Comment by larsop** [comment]
When doing each [heavy IO operations  in two stages]( https://github.com/larsop/resolve-overlap-and-gap/commit/040889f47d415a03db428dadca453ab521ebbadb) where the first stage is with out try catch and by setting hudge mem the  PostgreSQL lightweight locks is not a big problem any more. I have been running testes with 50 concurrent threads against the one Postgis Topology layer and works OK.
