### ISSUE TITLE
do "resolve_overlap_and_gap-pre.pl" failed, '.' is no longer in @INC

### ISSUE THREAD

**Issue by strk** [larsop/resolve-overlap-and-gap#6]
Output of `make check` on my system:
```
PostgreSQL 9.6.9 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0, 64-bit
  Postgis 2.5.4 - r17978 - 2020-04-20 15:04:07
  scripts 2.5.4 r17978
  GEOS: 3.9.0dev-CAPI-1.14.0
  PROJ: Rel. 7.0.0, March 1st, 2020

Running tests

do "resolve_overlap_and_gap-pre.pl" failed, '.' is no longer in @INC; did you mean do "./resolve_overlap_and_gap-pre.pl"? at ./run_test.pl line 617.
 resolve_overlap_and_gap ... ok 
 uninstall .. ok (4581)

Run tests: 2
Failed: 0
```

Two concerns:

 1. The "failed" message (why it fails ? should we fix?)
 2. The final report of 0 failures (did we not have a failure?)

It looks to me that the run_test.pl script was copied from PostGIS so possibly the second concern should be addressed upstream (handle that failure from within run_test.pl). The first concern most probably belongs here.

**Comment by strk** [comment]
I've updated original submission of this ticket, for those receiving emails upon ticket creation (I dubt github sends another mail for the correction).

**Comment by strk** [comment]
I've pushed a fix for the failure (first issue) as part of PR #5

**Comment by strk** [comment]
As per second issue, it looks like a newer version of {{{ run_test.pl }}} from upstream PostGIS had that one fixed already, but upgrading would make adaptation slightly harder so not sure it's worth the trouble at the moment.

**Comment by larsop** [comment]
Since I use commit of subtrans and Postgres procedures it will not run on Postgres 9.6. I have mostly tested on Postgres 11 and 12.

**Comment by strk** [comment]
> Since I use commit of subtrans and Postgres procedures it will not run on Postgres 9.6. I have mostly tested on Postgres 11 and 12.

You mean tests are silently skip if I'm running 9.6 ? Becuase you can see _something_ did run.
Shall I file another ticket to tackle that "all-success" response ?

**Comment by strk** [comment]
Ok, with this fix I actually see the test fails, correctly:
> +ERROR:  syntax error at or near "CALL" at character 1

So no need to another issue for that. Will just install and switch to PostgreSQL 12
