### ISSUE TITLE
Duplicate geometry from 2 different faces

### ISSUE THREAD

**Issue by larsop** [larsop/resolve-overlap-and-gap#8]
I have not managed to write SQL to find them, but what I see that we a lot cases like this.

`SELECT distinct fl.face_id
from 
test_topo_ar50_t11.edge_data e, 
test_topo_ar50_t11.face fl ,
test_topo_ar50_t11.face fr  
where e.end_node = e.start_node 
and e.left_face = fl.face_id
and e.right_face = fr.face_id
and (ST_CoveredBy(fl.mbr,fr.mbr) or ST_CoveredBy(fr.mbr,fl.mbr))`

but many of them are ok . 

How and when is it  decided what face to connect to ?

**Comment by strk** [comment]
Your query selects _closed_ edges (end_node = start_node). These are rings. Necessarely have an internal face and an external face (left and right, depending on orientation of the ring).

Then, you check if any of the two faces covers the other.

This will _always_ be the case for a valid topology. The bounding box of the EXTERNAL face will always cover the bounding box of the INTERNAL face.

The only exception would be outermost rings, having the UNIVERSE face as the external face.
As the UNIVERSE face has a NULL bounding box, those predicates will always return null...

**Comment by strk** [comment]
> How and when is it decided what face to connect to ?

Edges are always connected to 2 faces unless dangling or isolated.
For one face they are part one of one of its interior rings, for the other they are part of its exterior ring.

**Comment by larsop** [comment]
If you look at the attached picture, the problem is this polygon is returned by two different faces (face   53852 and 320071) 

`
select ST_GeometryType(st_getFaceGeometry('topo_sr16_mdata_01',320071));
 st_geometrytype 
-----------------
 ST_MultiPolygon
(1 row)

select ST_area(st_getFaceGeometry('topo_sr16_mdata_01',320071));
      st_area      
-------------------
 4302904.130024648
(1 row)

select ST_area(st_getFaceGeometry('topo_sr16_mdata_01',53852));
    st_area    
---------------
 5792.91015625
(1 row)

SELECT ST_area(ST_Intersection(st_getFaceGeometry('topo_sr16_mdata_01', 53852), st_getFaceGeometry('topo_sr16_mdata_01',320071)));
    st_area    
---------------
 5792.91015625
(1 row)

`


![Screenshot 2020-04-24 at 12 30 32](https://user-images.githubusercontent.com/5681424/80203422-697f0500-8627-11ea-8553-a5c5e51fe256.png)

**Comment by strk** [comment]
st_getFaceGeometry should NEVER return a multi-polygon. If that happens, the topology is corrupted.
I guess I could change ST_GetFaceGeometry to throw an exception, in that case, or at least print a WARNING. Anyway, it should NOT happen, with a valid topology.

**Comment by larsop** [comment]
> st_getFaceGeometry should NEVER return a multi-polygon. If that happens, the topology is corrupted.
> I guess I could change ST_GetFaceGeometry to throw an exception, in that case, or at least print a WARNING. Anyway, it should NOT happen, with a valid topology.

This is great info,  a warning is ok.

Is it possible for me to remove this invalid face ?

I wonder if this is related to  both duplicates and null values for face geometry ?

**Comment by strk** [comment]
Faces are really only virtual, in topology primitive tables. All that exists about a face is a set of edges advertising that face _number_ being on one or both of their sides. So what's invalid is the attribute value for edges, in that the _same_ face (supposedly) is advertised to be bound by multiple "edge rings". QGIS TopoViewer plugin may help finding out where such edges are. The function https://postgis.net/docs/manual-3.0/GetRingEdges.html may then help obtaining a list of ALL EDGES partecipating in a ring, giving you one chance to update them all at once so they have a (for example) _new_ face identifier on their sides.

Assuming edge-linking is ok (next left/right edge attribute on edge_data), the https://postgis.net/docs/manual-3.0/TopologyPolygonize.html function may be able to do this face-tagging for you, but it would imply preparing the topology so to initially DROP all records from the "face" table, and set the universal face as being on both sides of all edges. It's a pretty destructive operation, and Polygonizer would run against the whole topology (probably very very CPU intensive)

**Comment by larsop** [comment]
This seems have to solved by running step 3 (where we add lines that that crosses cell borders) in a single thread
