### ISSUE TITLE
make check modifies source tree

### ISSUE THREAD

**Issue by strk** [larsop/resolve-overlap-and-gap#9]
After running `make check`, the source tree results modified:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/test/sql/regress/resolve_overlap_and_gap-pre-def.sql
```

This is bad behaviour, if the file needs be modified it's better to move it elsewhere

**Comment by strk** [comment]
As I found references to `submodules` in the code handling that file, I'll mention I did not download submodules:
```
 $ git submodule status
-66c8267590543951c1b5088ff021cc5b70e0acff submodule/content_balanced_grid
-3666f18845da271026b17fcc1d3e2eb110adff26 submodule/find-overlap-and-gap
-d13ece235db06b52938cd1bdb1d3fa55e61cfbdb submodule/pgtopo_update_sql
-882e9cbe0226c1360f9f41adaa3d8dfb48d1b434 submodule/postgres_execute_parallel
```

**Comment by larsop** [comment]
Is it ok that I put src/test/sql/regress/resolve_overlap_and_gap-pre-def.sql in the git ignore file ?

**Comment by larsop** [comment]
Har lagt til .gitigonre file på master

**Comment by larsop** [comment]
About sub modules, I tried to set up so they should be downloaded by itself, to make it easier to use.

**Comment by strk** [comment]
> Is it ok that I put src/test/sql/regress/resolve_overlap_and_gap-pre-def.sql in the git ignore file ?

If it does NOT belong to the repository it should be removed from it (`git rm src/test/sql/regress/resolve_overlap_and_gap-pre-def.sql`). Once it's removed, it is good to put it in the git ignore file (which needs to be added to the repository)

**Comment by strk** [comment]
> About sub modules, I tried to set up so they should be downloaded by itself, to make it easier to use.

`git clone git@github.com:larsop/resolve-overlap-and-gap.git` did not download them (is what I did).

Adding a `--recursive` switch to `git clone` above would have done that (may be worth recommending that in the README.md file)



----

Please see #10 for the removal of generated file

**Comment by larsop** [comment]
Thanks updated README.md
